# Generated by Django 4.2.4 on 2023-08-07 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
