# Generated by Django 4.2.4 on 2023-08-07 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={},
        ),
    ]
