# Generated by Django 4.2.4 on 2023-08-13 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
